var data = [{'ACCION':'Se inicia Sicret.','PROBLEMA':'Se visualiza que el cuadro de identificación se ubica en la parte inferior de la barra de menú, cuando la resolución es reducida.','NECESITA':'Se necesita que el cuadro de identificación se encuentre alineado con la barra de menú, sin que esta se ubique en la parte inferior.','APLICACION':'/MenuCorpSicret2013','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'1'}	,
{'ACCION':'Se inicia Sicret y se identifica con usuario y contraseña.','PROBLEMA':'Se visualiza que el cuadro de usuario ya identificado se ubica en la parte inferior de la barra de menú, cuando la resolución es reducida.','NECESITA':'Se necesita que el cuadro del usuario ya identificado se encuentre alineado con la barra de menú, sin que esta se ubique en la parte inferior.','APLICACION':'/MenuCorpSicret2013','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'2','ID_GRUPO':'1'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Tipos actividades".','PROBLEMA':'Al intentar realizar filtro de busqueda de "Tipos Actividades" no carga combobox con prioridad.','NECESITA':'Se necesita que se cargue combobox con prioridad para realizar el filtro de busqueda correctamente en "Tipos Actividades"','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Estado y SubEstados".','PROBLEMA':'En el formulario para realizar filtro de busqueda el combobox de actividad sobre pasa los margenes del contenido de la pagina.','NECESITA':'Se debe ajustar el ancho del combobox de actividad a los margenes del contenido de la pagina.','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'2','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Politicas".','PROBLEMA':'Al intentar realizar filtro de busqueda de "Politicas" no carga combobox con Objeto.','NECESITA':'Se necesita que se cargue combobox con Objeto para realizar el filtro de busqueda correctamente en "Politicas"','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'3','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Condiciones".','PROBLEMA':'Al intentar realizar filtro de busqueda de "Condiciones" no carga combobox con Objeto, combobox Y botones se encuentran fuera de los margenes.','NECESITA':'Se necesita que se cargue combobox con Objeto para realizar el filtro de busqueda correctamente en "Condiciones" y se debe ajustar los combobox y botones a los margenes del contenido de la pagina.','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'4','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Workflows".','PROBLEMA':'Al intentar realizar filtro de busqueda de "Workflows" no carga combobox con Objeto.','NECESITA':'Se necesita que se cargue combobox con Objeto para realizar el filtro de busqueda correctamente en "Workflows".','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'5','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Administracion Workflows / Plantillas Actividades".','PROBLEMA':'Al intentar realizar filtro de busqueda de "Plantillas Actividades" en el campo Nombre Plantilla y Nombre Actividades muestra texto "Seleccione" por defecto. No es posible realizar el filtro de busqueda, ya que no encuentra ninguna plantilla.','NECESITA':'Se debe limpiar los campos Nombre Plantilla y Nombre Actividades. Se debe realizar filtro correctamente.','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'6','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion "Sistema de Instalaciones" , luego se selecciona submenu "Ver Detalle Solicitud"','PROBLEMA':'Al realizar el filtro de busqueda y seleccionar una solicitud, se despliega el detalle de la solicitud, si se selecciona un campo de texto cualquiera y se presiona la tecla retroceso (borrar), la pantalla queda en una página de error.','NECESITA':'Se debe bloquear el funcionamiento de la tecla retroceso en los campos de texto que solo muetren información, a través de Javascript, o cambiar éstos por tags labels.','APLICACION':'/Instalaciones','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'7','ID_GRUPO':'2'}	,
{'ACCION':'Se ingresa a Sicret, aplicacion administrador de Puertos y se selecciona Historico de Bajas.','PROBLEMA':'Se visualiza Scroll inferior, cuando no es necesario. El contenido de la pagina sobrepasa el marge derecho y al realizar busqueda de historico de Baja de una instancia, la tabla de resultado es demaciado ancha para el contenido de la pagina.  ','NECESITA':'Se necesita que se visualize el Scroll cuando sea necesario. El contenido de la pagina no debe sobrepasar el margen de esta.','APLICACION':'/AdministradorPuertos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'3'}	,
{'ACCION':'Se inicia Sicret, Se ingresa a Mantenedores Sicret y se selecciona Manenedor de Tipo Actividad y Mantenedor de Plantilla. ','PROBLEMA':'Se visualiza que no se ve margen del lado derecho del contenido de ambos mantenedores.','NECESITA':'Ajustar el Margen, para que se vea proporcional el margen izquierdo y derecho.','APLICACION':'/MantenedorSicret','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'1','ID_GRUPO':'4'}	,
{'ACCION':'Se inicia Sicret, Se ingresa a Mantenedores Sicret y se selecciona Mantenedor de Tipo Actividad y Mantenedor de Plantilla. ','PROBLEMA':'Al presionar el botón Crear Actividad, se levanta la ventana modal Nuevo Tipo de Actividad, la barra de botones de navegación del Wizard se visualiza corrido hacia el final de la página.','NECESITA':'Ajustar la posición del div de la botonera de navegación de SmartWizard','APLICACION':'/MantenedorSicret','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'2','ID_GRUPO':'4'}	,
{'ACCION':'Se inicia Sicret, Se ingresa a Mantenedores Sicret y se selecciona Mantenedor de Tipo Actividad y Mantenedor de Plantilla. ','PROBLEMA':'Al presionar el botón Crear Actividad, se levanta la ventana modal Nuevo Tipo de Actividad, al crear una actividad aparece un dialogo de confirmación, al cancelar la creación de actividad la ventana modal Nuevo Tipo de Actividad se mueve y el título con su botón cerrar se esconde.','NECESITA':'Ajustar CSS y revisar el z-index de cada una de las ventanas modal.','APLICACION':'/MantenedorSicret','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'3','ID_GRUPO':'4'}	,
{'ACCION':'Se inicia Sicret, Se ingresa a Mantenedores Sicret y se selecciona Mantenedor de Agrupaciones. ','PROBLEMA':'Si se realiza una búsqueda de agrupaciones donde se despliega más de un resultado y se exporta a Excel, se creará un archivo con la información filtrada. Sin embargo, si se ingresa a la opción de modificar uno de los registros y se cancela, seguirá mostrando la lista de resultados antes filtrada, al presionar exportar a excel se creará un archivo con el registro que se intentó modificar y no de la lista total filtrada.','NECESITA':'Se debe revisar el objeto o la lista de objetos que se utiliza en la capa action del mantenedor de agrupaciones, lo más probable es que se esté reutilizando el mismo tanto para el listado de resultados, el despliegue de información al modificar y al exportar a excel. Se necesita realizar una consulta nueva para exportar a excel, tomando en cuenta los datos antes filtrados en el formulario de búsqueda.','APLICACION':'/MantenedorSicret','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'4','ID_GRUPO':'4'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos"','PROBLEMA':'Se visualiza que el interior del filtro de búsqueda del "Gestor de Reclamos" se encuentra fuera del margen en el lado derecho, en comparación a la barra de menú superior.','NECESITA':'Se debe ajustar el interior del formulario de búsqueda de "Gestor de Reclamos" para que este se mantenga al interior del margen, respetando el ancho de la barra de menú superior.','APLICACION':'/AtencionClientes','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo"','PROBLEMA':'Se visualiza que el interior de la pantalla de "Crear reclamo" se encuentra con textbox, combobox, buttons y fieldset fuera del margen en lado derecho del div que los contiene.','NECESITA':'Se debe ajustar el contenido mencionado dentro de margen que contiene los campos de "Crear Reclamo"','APLICACION':'/AtencionClientes','IMPACTO':'Medio','PARIDAD':'No','ID_ERROR':'2','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo" con filtro de búsqueda por reclamo en formulario, seleccionado.','PROBLEMA':'Se visualiza que el interior de la pantalla de "Consultar reclamo" se encuentra con textbox, combobox, buttons y fieldset fuera del margen en lado derecho del div que los contiene.','NECESITA':'Se debe ajustar el contenido mencionado dentro de margen que contiene los campos de "Consultar Reclamo"','APLICACION':'/AtencionClientes','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'3','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo"','PROBLEMA':'En la sección Cliente, campo Rut, es posible ingresar caracteres alfanuméricos, si se presiona el botón (…) al costado del campo Rut, se despliega una ventana emergente, y se busca por un valor alfanumérico se genera un error, mostrando parte de código en la pantalla.','NECESITA':'Se debe agregar una validación para que el campo Rut acepte solamente valores numéricos.','APLICACION':'/AtencionClientes','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'4','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo"','PROBLEMA':'En la sección Cliente, link Equipos Instancias, envía a la instancia localhost y no a la instancia a la que estoy consultando.','NECESITA':'Se debe cambiar la dirección a la que está apuntando el link a la instancia correspondiente.','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'5','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo"','PROBLEMA':'En la sección Estado/Propiedad, al costado derecho del campo prioridad, está el botón (…), cuando se presiona, se levanta una ventana emergente. En la ventana emergente existe un botón llamado Cancelar, el cual al presionarlo se cierra la ventana emergente y la ventana de Crear Reclamo se queda en blanco.','NECESITA':'Se debe revisar la función que se está ejecutando al presionar el botón cancelar, verificando si es un problema Javascript o Java','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'6','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Gestor de Reclamos", luego se pincha botón "ver / crear/ modificar reclamo"','PROBLEMA':'En la sección Bitácoras del reclamo, al presionar el botón INGRESAR BITÁCORA, se despliega una ventana emergente. Si no se ingresan comentarios y se hace clic sobre el botón GUARDAR,se cierra la ventana emergente y la pantalla de Crear Reclamo Se queda en blanco o queda hasta la mitad de los datos. Esto se probó al crear un nuevo reclamo.','NECESITA':'Se debe verificar la funcionalidad del botón guardar, validando que exista por lo menos 1 comentario para que se puedan guardar los cambios. Se debe revisar el motivo por el cual la pantalla padre queda en blanco.','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'7','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Crear Reclamo Padre"','PROBLEMA':'Se visualiza que el interior de la pantalla de "Crear Reclamo Padre" se encuentra con textbox y combobox más distribuidos y de ancho inadecuado para el contenido de estos.','NECESITA':'Se debe ajustar el contenido mencionado dentro de textbox y combobox, y distribuirlos de forma ordenada.','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'8','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Crear Reclamo Padre" y luego a ver tickets asociados.','PROBLEMA':'Se visualiza ventana de dialogo, sin boton cerrar, además al pinchar volver en ella aparece error.','NECESITA':'Se debe agregar un botón para cerrar la ventana modal y solucionar funcionamiento de botón volver.','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'9','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Gestionar Reclamos / Crear Reclamo Padre" y luego a ver tickets asociados.','PROBLEMA':'Ventana modal se desplaza a la parte inferior de la página si se intenta arrastrar haciendo click en su título.','NECESITA':'Se debe revisar la opción "draggable jquery" y su integración en el sistema.','APLICACION':'/AtencionClientes','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'10','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Consulta / Ticket Pendientes por usuario" .','PROBLEMA':'Al iniciar esta página se pierde el contexto del Menú de Sistema de Atencion clientes.','NECESITA':'Se debe abrir una pestaña nueva de "Ticket Pendientes por usuario" para poder volver al menú de "Sistema de Atencion Clientes".','APLICACION':'/AtencionClientes','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'11','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opcion "Administracion / Mantenedor de Síntomas" .','PROBLEMA':'Se visualiza 2 veces el titulo mantenedor de síntomas y se encuentra contenido fuera del margen del contenedor de la página.','NECESITA':'Se debe ajustar el contenido al margen del contenedor de la página.','APLICACION':'/AtencionClientes','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'12','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opción "Reportes Operativos / Reporte Tickets Realizados" .','PROBLEMA':'Se visualiza que el contenido de "Reporte Tickets Realizados" se encuentra sobre el ancho de la barra de menú superior.','NECESITA':'Se debe ajustar el contenido al ancho de la barra de menú superior.','APLICACION':'/AtencionClientes','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'13','ID_GRUPO':'5'}	,
{'ACCION':'Se inicia Sicret y se ingresa a aplicación "Sistema Atencion Clientes", opcion "indicadores de Operación- gestión/ Reporte de Velocidad" .','PROBLEMA':'Los gráficos que se visualizan se encuentran sobre el margen derecho máximo.','NECESITA':'Se debe ajustar los gráficos visualizados al margen derecho maximo, para evitar que aparezca scroll inferior.','APLICACION':'/AtencionClientes','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'14','ID_GRUPO':'5'}	,
{'ACCION':'Se selecciona "Todas las actividades" en el menú de "Sistema de Atencion Clientes".','PROBLEMA':'Se visualiza que los textbox y botones se encuentran desalineados y con mala distribución, al ser una resolucion baja.','NECESITA':'Se debe distribuir de mejor manera los textbox y botones en el interior de la pantalla de Actividades.','APLICACION':'/GestorActividades','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'1','ID_GRUPO':'6'}	,
{'ACCION':'Se selecciona "Consulta / Consulta Pefil Clientes" en el menú de "Sistema de Atencion Clientes".','PROBLEMA':'Se visualiza que los textbox se encuentran  alineados a la derecha fuera de los márgenes del interior de la pantalla.','NECESITA':'Se debe ajustar los textbox al margen que contiene la página.','APLICACION':'/PerfilCliente','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'1','ID_GRUPO':'7'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'Se visualiza que las letras en los textbox del formulario de "criterio de búsqueda" no se ven de manera completa en parte inferior.','NECESITA':'Se debe ajustar la altura de los textbox, para visualizar de mejor manera las letras de su interior.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'1','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'Se visualiza mensaje de alerta con ancho muy reducido para el tamaño de letra.','NECESITA':'Se debe ajustar el ancho del mensaje de alerta para que la información entregada al usuario sea más legible.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'2','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'El campo rut no valida el formato ingresado, se pueden ingresar letras en un campo que solo debería aceptar números y al apretar el botón buscar la pantalla queda en blanco con un titulo de Error.','NECESITA':'Se debe validar que el formato ingresado sea un rut válido y/o que el campo rut permita el ingreso de solo números, ya que es el dígito verificador el que comple con tal característica.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'3','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'Al agregar un contacto, se llena el formulario con los datos obligatorios, se presiona el botón crear y se lanza el mensaje Debe Completar el Medio de Contacto y Detalle., campos que están ocultos, no siendo visibles al usuario.','NECESITA':'Se debe cambiar la visibilidad de los campos requeridos para completar la creación de un contacto para que puedan ser llenados.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'4','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'Al agregar un contacto, no se valida que los datos ingresados en el campo rut tengan el formato correcto, incluso al presionar el botón crear.','NECESITA':'Se debe validar el formato de rut, con los campos rut y digito verificador.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'5','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'El formulario de búsqueda, tiene Criterios de búsqueda, sin embargo solo se filtra por el campor rut, aunque se escriban datos en los campos nombre, fecha o usuario de moodificación, son ignorados y reemplazados por los del último cambio realizado. Si el filtrado se realiza solamente por rut y los demás son ignorados deberían estar bloqueados porque producen confución al usuario final.','NECESITA':'Se deben considerar los filtros de los campos en los cuales se pueden editar o bloquearlos para que no se ingresen datos de búsqueda en ellos.','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'6','ID_GRUPO':'8'}	,
{'ACCION':'Se selecciona "Consulta de Contactos" en el "Gestor de Reclamos"','PROBLEMA':'Al ver un contacto, la información de los campos se puede volver ilegible porque el tamaño de los campos es fijo e igual para todos los casos. Además, existe un scroll que no tiene mucho sentido, porque la pantalla no se adapta al espacio total, sino que se muestra un espacio en blanco.','NECESITA':'se debe aumentar el tamaño de los campos, para datos como email o tipo','APLICACION':'/Contactos','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'7','ID_GRUPO':'8'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Resumen de Cliente". Se realiza búsqueda y se selecciona una cuenta de servicio de cliente. Se selecciona tipo solicitud "Agregar/ Modificar Publicación en Guia" .','PROBLEMA':'Se levanta ventana emergente y se selecciona "Crea"','NECESITA':'Se debe ajustar la altura de los textbox, para visualizar de mejor manera las letras de su interior.','APLICACION':'/GestionComercial','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Resumen de Cliente". Se realiza búsqueda y se selecciona una cuenta de servicio de cliente. Se selecciona tipo solicitud "Traslado" .','PROBLEMA':'En el paso servicio solicitado se levanta ventana emergente en la cual los títulos de las tablas se encuentran sobre el margen del lado derecho.','NECESITA':'Se debe ajustar los títulos de las tablas al margen que los contiene.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'2','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Resumen de Cliente". Se realiza búsqueda y se selecciona una cuenta de servicio de cliente. Se selecciona tipo solicitud "Traspaso de Propiedad" .','PROBLEMA':'En el paso de "Buscar/ Crear Nuevo Cliente" aparece popup, en el cual el texto se encuentra erróneo. ','NECESITA':'Se debe cambiar el texto del mensaje de página web, de manera correcta.','APLICACION':'/GestionComercial','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'3','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Resumen de Cliente". Se realiza búsqueda y se selecciona una cuenta de servicio de cliente, luego una instancia. Se selecciona tipo solicitud "Cambio de N°" .','PROBLEMA':'En la pantalla de cambio de numeración, los textbox y tabla con activos disponibles se encuentra fuera de los márgenes que se contienen. ','NECESITA':'Se debe ajustar los textbox y tabla de activos disponibles al interior de la página, agrupar de mejor maneras los objetos en la ventana.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'4','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Resumen de Cliente". Se realiza búsqueda y se selecciona una cuenta de servicio de cliente, luego una instancia. Se selecciona tipo solicitud "Migración FTTH" .','PROBLEMA':'En la pantalla de migración a ftth se encuentra tabla de "instancias con dirección en conflicto" en un contenedor pequeño, el cual se supera sus márgenes. ','NECESITA':'Contenedor de la tabla "instancias con dirección en conflicto" debe quedar dentro de los márgenes del contenedor. El contenedor debe igualar el ancho de los márgenes superiores.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'5','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Gestor de Solicitud". Se realiza búsqueda y se pincha el signo + para ver instancias asociadas a la solicitud.','PROBLEMA':'El cuadro que muestra debajo de cada solicitud de la tabla, no tiene el mismo ancho que tabla superior.','NECESITA':'Se debe igualar el ancho del contenedor de las instancias asociadas a la solicitud, al igual que el de los datos de la solicitud superior.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'6','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente / Gestor de Solicitud". Se realiza búsqueda y se selecciona operación "Modificar Contacto Cliente".','PROBLEMA':'En la pantalla "todos los contactos" se encuentra tabla resultado de búsqueda, fuera de los márgenes que la contienen.','NECESITA':'Se debe ajustar la tabla de resultado de búsqueda Mencionada a los márgenes.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'7','ID_GRUPO':'9'}	,
{'ACCION':'Se revisa solicitud y se intenta agregar productos a la instancia.','PROBLEMA':'Se levanta pantalla "Agregar Productos Instancia" en la cual el cuadro de "Detalle Instancia" tiene un ancho menor a los contenedores anteriores y no se encuentran alineados.','NECESITA':'Se debe igualar el ancho de "Detalle Instancia" al igual que los contenedores anteriores.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'8','ID_GRUPO':'9'}	,
{'ACCION':'Se revisa solicitud y se intenta agregar productos a la instancia.','PROBLEMA':'Se levanta pantalla "Agregar Productos Instancia" en la cual el cuadro de "Parámetros" tiene los títulos sobre el margen en su lado izquierdo.','NECESITA':'Se debe dejar los títulos mencionados en el interior del cuadro de parámetros.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'No','ID_ERROR':'9','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se pincha "Venta y Mantencion de Cliente/ Todas las Actividades".','PROBLEMA':'Se visualiza que el contenido es más ancho que el titulo donde se encuentra menu.','NECESITA':'Se debe igualar el ancho del contenido al del título, para que se vea alineado.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'10','ID_GRUPO':'9'}	,
{'ACCION':'Se selecciona visualizar o modificar las actividades, ya haciendo el filtro de actividad.','PROBLEMA':'Se levanta ventana emergente y se visualiza que el contenido al visualizar o modificar actividades es más ancho que el titulo del Sistema de Gestión Comercial.','NECESITA':'Se debe ajustar el contenido al contenedor del menú mencionado.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'11','ID_GRUPO':'9'}	,
{'ACCION':'Se realiza una búsqueda de actividades y muestra el resultado de Búsqueda.','PROBLEMA':'Se exporta a excel el resultado y se visualiza que el campo de reprocesada no tiene valor, cuando en el filtro si se encuentra.','NECESITA':'Agregar el valor de reprocesada si o no, según corresponda.','APLICACION':'/GestionComercial','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'12','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Portabilidad Numérica / Formularios Portabilidad"','PROBLEMA':'Al dar click directamente en "formularios Portabilidad", se puede ver los directorios del Contexto de GestionComercial2.','NECESITA':'Al dar click en "Formularios Portabilidad" no debe realizar ninguna acción.','APLICACION':'/GestionComercial','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'13','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Gestor de Numeración / Marcar Tipo de Numeración"','PROBLEMA':'Al seleccionar Marcar Tipo de Numeración, la pantalla se queda en blanco y no muestra contenido.','NECESITA':'Se debe revisar porque se queda en blanco el contenido de la página seleccionada.','APLICACION':'/GestionComercial','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'14','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Reportes Operativos / Actividades Asignaciones Pendientes a la fecha"','PROBLEMA':'Se realiza una búsqueda, la cual muestra una tabla que se ubica fuera de los márgenes del lado derecho.','NECESITA':'Se debe ajustar tabla para que se ubique dentro de los márgenes del contenedor de la página.','APLICACION':'/GestionComercial','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'15','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Administrador Lista Negra/ Administrador Lista Negra"','PROBLEMA':'Se ingresa a "Administrador Lista Negra" y se encuentra, label y textbox fuera de los márgenes del contenido de la página.','NECESITA':'Se debe ajustar el label y textbox dentro del margen de la página.','APLICACION':'/GestionComercial','IMPACTO':'Medio','PARIDAD':'Sí','ID_ERROR':'16','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Override/ Aprobación"','PROBLEMA':'Al ingresar a pantalla "Aprobación" se encuentra combobox de usuarios no cargados para realizar filtro de búsqueda.','NECESITA':'Se debe cargar combobox de usuarios y intentar realizar búsqueda exitosa.','APLICACION':'/GestionComercial','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'17','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Administrador de Bajas por Deudas/ Bajas Masivas por deuda"','PROBLEMA':'Al ingresar a pantalla de "Bajas Masivas por deuda" se encuentra botones fuera de los márgenes.','NECESITA':'Se debe ajustar botones al interior de los márgenes que contienen la página.','APLICACION':'/GestionComercial','IMPACTO':'Bajo','PARIDAD':'Sí','ID_ERROR':'18','ID_GRUPO':'9'}	,
{'ACCION':'Se ingresa a Sicret, "Sistema Gestión Comercial" y se selecciona "Ventas de Equipos y Otros"','PROBLEMA':'Al ingresar a "Ventas de Equipos y Otros" no muestra contenido.','NECESITA':'Se debe mostrar la página, ya que solo muestra un contenedor rojo.','APLICACION':'/SVentaProducto','IMPACTO':'Alto','PARIDAD':'Sí','ID_ERROR':'1','ID_GRUPO':'10'}	
];


//Data de valores de tablas de Resumen
function obtenerNombres(data){
	var nombres = [];
	var impactos = [];
    var paridad = [];
	var datos = {};
	for (var i = 0; i < data.length; i++) {
		nombres.push(data[i].APLICACION);
		impactos.push(data[i].IMPACTO);
        paridad.push(data[i].PARIDAD);
	}
	datos = {
		'nombres':nombres,
		'impactos':impactos,
        'paridad':paridad
	}
	return datos
}

Array.prototype.unique=function(a){
  return function(){return this.filter(a)}}(function(a,b,c){return c.indexOf(a,b+1)<0
});

function nuevaData(){
	var nombres = obtenerNombres(data).nombres.unique();
	var impactos = obtenerNombres(data).impactos.unique();
    
	var nuevaData = [];
    var nuevaDataTotal = [];
    
	for (var i = 0; i < nombres.length; i++) {
		for(var j = 0; j < impactos.length; j++){
            var valor = $.grep(data, function (e) { return e.APLICACION == nombres[i] && e.IMPACTO ==impactos[j]}).length;
            
			nuevaData.push({
				'APLICACION': nombres[i].split('/')[1] ,
				'IMPACTO'	: impactos[j], 
				'VALOR'		: valor.toString()
		});
           
	   }
        var valorTotal = $.grep(data, function (e) { return e.APLICACION == nombres[i]}).length;
         nuevaDataTotal.push({
              'APLICACION'  : nombres[i].split('/')[1] ,
              'IMPACTO'	    : 'Total', 
              'VALOR'		: valorTotal.toString()
          });
    }
              
    nuevaData = nuevaData.concat(nuevaDataTotal);
	return nuevaData;
}

function obtenerParidad(){
    var nombres = obtenerNombres(data).nombres.unique();
    var paridad = obtenerNombres(data).paridad.unique();
    var nuevaData = [];
    for (var i = 0; i < nombres.length; i++) {
		for(var j = 0; j < paridad.length; j++){
            var valor = $.grep(data, function (e) { return e.APLICACION == nombres[i] && e.PARIDAD ==paridad[j]}).length;
            nuevaData.push({
				'APLICACION': nombres[i].split('/')[1] ,
				'PARIDAD'	: paridad[j], 
				'VALOR'		: valor.toString()
		});
        }
    }
    return nuevaData;
}

var resumenData = nuevaData()